SEED: 7
DEBUG: True
LOG_FREQ: 100
SAVE_CHECKPOINTS: [ 20 ]
INFERENCE_CHECKPOINT: 20

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 20
  OPTIMIZER: 'adamw'

MODEL:
  DUALSTREAM: True
  STREAM1:
    TYPE: 'resnet'
    SIZE: 18
    PRETRAINED: True
    OUT_CHANNELS: 1
    IN_CHANNELS: 4
  STREAM2:
    TYPE: 'resnet'
    SIZE: 18
    PRETRAINED: True
    OUT_CHANNELS: 1
    IN_CHANNELS: 1
  LOSS_TYPE: 'L2'
  OUT_CHANNELS: 1
  DISABLE_FUSION_LOSS: False

DATALOADER:
  FEATURE_STREAM1: 's2'
  FEATURE_STREAM2: 'bf'
  LOG_POP: False
  NUM_WORKER: 2
  SHUFFLE: True
  PATCH_SIZE: 200
  VHR_MAX_REFLECTANCE: 5_000
  VHR_BAND_INDICES: [ 0, 1, 2 ]
  S2_BAND_INDICES: [ 2, 1, 0, 3 ]
  INCLUDE_UNLABELED: False

DATASET:
  LABELED_CITIES: [ 'dakar' ]
  UNLABELED_CITIES: [ 'nairobi', 'daressalaam' ]
  CENSUS_EVALUATION_CITIES: [ 'dakar', 'nairobi', 'daressalaam']

AUGMENTATION:
  STREAM1:
    RANDOM_FLIP: True
    RANDOM_ROTATE: True
    COLOR_SHIFT: False
    GAMMA_CORRECTION: False
    DOWNSAMPLING: 1
  STREAM2:
    RANDOM_FLIP: True
    RANDOM_ROTATE: True
    COLOR_SHIFT: False
    GAMMA_CORRECTION: False
    DOWNSAMPLING: 1
